services:
  nextjs:
    build: .
    restart: unless-stopped
    expose:
      - "3005"
    networks:
      - public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`andrewdover.com`) || Host(`www.andrewdover.com`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"
      - "traefik.http.services.portfolio.loadbalancer.server.port=3005"

networks:
  public:
    external: true